name: poetsd8
proxy:
  appserver:
    - poetsd8.lndo.site
  yakbak:
    - yakbakpoets.lndo.site
excludes:
  - node_modules
env_file:
  - .env
services:
  appserver:
    type: node:10
    command: cp -n /app/.env.example /app/.env && yarn dev
    build:
      - yarn install
    overrides:
      environment:
        PORT: 80
        HOST: "0.0.0.0"
  yakbak:
    type: node:10
    command: node /app/proxy.js
    build:
      - yarn install
  codeception:
    type: compose
    services:
      image: codeception/codeceptjs
      command: /codecept/docker/entrypoint
tooling:
  yarn:
    service: appserver
  npm:
    service: appserver
  node:
    service: appserver
  nuxt:
    cmd: /app/node_modules/.bin/nuxt
    service: appserver
  test:
    cmd: yarn test
    service: codeception
  codecept:
    cmd: /app/node_modules/.bin/codeceptjs
    service: appserver
