
name: app
type: nodejs:10
dependencies:
  nodejs:
    yarn: latest
hooks:
  build: |
    yarn install
    yarn generate
    yarn build-storybook
size: S
disk: 256
web:
  commands:
    start: sleep infinity
