# App and type
name: app
type: nodejs:10

# Dependencies
dependencies:
  nodejs:
    yarn: latest

# Disk and mounts
disk: 4000
mounts:
  '/tmp': 'shared:files/tmp'

# Boot up
web:
  commands:
    start: yarn start

# Hooks
hooks:
  build: |
    rm -rf /app/.nuxt
    yarn install
    yarn build
    # We need to do the below manually for now
    # See: https://github.com/yarnpkg/yarn/issues/6685
    yarn cache clean
    rm -rf /tmp/yarn--*

# crons
crons:
  sitemap:
    spec: '22 2 1,15 * *'
    cmd: 'curl -I https://www.poets.org/sitemap.xml'
