
name: app
type: nodejs:10
dependencies:
  nodejs:
    yarn: latest
hooks:
  build: |
    yarn install
    yarn generate
size: S
disk: 256
web:
  commands:
    start: sleep infinity
  locations:
    '/':
      passthru: false
      root: 'dist'
      index:
        - index.html
      expires: 3d
      allow: false
      rules:
        \.(css|js|gif|jpe?g|png|ttf|eot|woff2?|otf|html|ico|svg?)$:
          allow: true
        ^/robots\.txt$:
          allow: true
        search_plus_index\.json$:
          allow: true
